using YOTO;

namespace YOTO
{
 public   enum MessageType {

     //登录相关的消息
     LOGIN_REQUEST = 1,
     LOGIN_RESPONSE = 2,
// 房间相关消息
     CREATE_ROOM_REQUEST = 3,
     CREATE_ROOM_RESPONSE = 4,
     JOIN_ROOM_REQUEST = 5,
     JOIN_ROOM_RESPONSE = 6,
     LEAVE_ROOM_REQUEST = 7,
     LEAVE_ROOM_RESPONSE = 8,
     PLAYER_READY_REQUEST = 9,
     PLAYER_READY_RESPONSE = 10,
     ROOM_LIST_REQUEST = 11,
     ROOM_LIST_RESPONSE = 12,

// 房间通知消息
     ROOM_PLAYER_JOIN = 13,
     ROOM_PLAYER_LEAVE = 14,
     ROOM_PLAYER_READY = 15,
     ROOM_GAME_START = 16,
     ROOM_GAME_END = 17,

// 游戏状态同步消息
     GAME_STATE_REQUEST = 30,
     // GAME_STATE_RESPONSE = 31,
     // GAME_STATE_UPDATE = 32,

// 心跳包消息
     HEARTBEAT_REQUEST = 100,
     HEARTBEAT_RESPONSE = 101,



//stock逻辑
     OPEN_STOCK_NOTIFY = 201,
     PLAYER_STOCK_MONEY_REQUEST = 202,//竞价
     PLAYER_STOCK_MONEY_RESPONSE = 203,//竞价
     PLAYER_STOCK_MONEY_NOTIFY = 204,//竞价
     COUNT_DOWN_NOTIFY = 205,//结算
     SECONED_REFRESH_NOTIFY = 206,//倒计时
     BUYING_END_NOTIFY = 207,
     GAME_FINISH_NOTIFY = 208,//游戏结束
//加钱：
     MONEY_CHANGE_REQUEST = 301,//钱变化
     MONEY_CHANGE_RESPONSE = 302,//钱变化
     MONEY_CHANGE_NOTIFY = 303,//钱变化

     //买东西
     PLAYER_BUY_THINGS_REQUEST=304,
     PLAYER_BUY_THINGS_RESPONSE = 305,
        
    }
 
}
